#!/bin/bash
clear
echo " Velocity"
echo " --------"
python ~/code/Misc/CalculatePersonalVelocity.py
echo
echo " Week Chart"
echo " ----------"
timew week
echo
echo " Day List"
echo " --------"
timew sum :ids 
echo " Meeting"
echo " -------"
/usr/local/bin/icalbuddy -npn -ea -nc -ps "/ » /" -eep "url",location,notes,attendees -ic "Calendar" eventsToday | uniq